name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Install CloudSim to local Maven repo
      run: mvn install:install-file -Dfile=lib/cloudsim-4.0.jar -DgroupId=org.cloudbus -DartifactId=cloudsim -Dversion=4.0 -Dpackaging=jar


    - name: Build with Maven
      run: mvn clean install
